# Default values for jetploymentchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

webserver:
  image: ~
  branch: master
  tag: ~
  pullPolicy: Always
  replicas: 1
  nodeSelector: {}
  resources: {}

app:
  port: 80
  repo: ~
  branch: master
  authMethod: ~
  env: development
  registry: ~
  deployKeyPath: /secrets/deploy-key
  repoClonePath: /repo
  mainColour: "#83a835"
  secrets:
    deployKey: deploy-key
    jetploymentSecrets: jetployment-secrets

ingress:
  webserver:
    path: ""
    annotations: {}
    tls: []
