apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: {{template "application.name" .}}
    component: webserver
    release: {{.Release.Name}}
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: {{template "application.name" .}}
      component: webserver
      release: {{.Release.Name}}
  template:
    metadata:
      annotations:
        checksum/jetployments-configmap: {{include (print $.Template.BasePath "/jet-config.yaml") . | sha256sum}}
      labels:
        app: {{template "application.name" .}}
        component: webserver
        release: {{.Release.Name}}
    spec:
      containers:
        - name: webserver
          image: {{template "webserver.image" .}}
          imagePullPolicy: Always
          ports:
            - name: webserver
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: "/secrets/deploy-key"
              name: deploy-key
          envFrom:
            - secretRef:
                name: {{ .Values.app.secrets.jetploymentSecrets }}
            - configMapRef:
                name: "{{template "application.name" .}}-env"
      volumes:
        - name: deploy-key
          secret:
            secretName: {{ .Values.app.secrets.deployKey }}
            defaultMode: 256
{{- if .Values.webserver.resources }}
          resources:
{{ toYaml .Values.webserver.resources | indent 12 }}
{{- end }}
      restartPolicy: Always
{{- if .Values.webserver.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.webserver.nodeSelector | indent 8 }}
{{- end }}
status: {}
