apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webserver
  labels:
    app: {{template "application.name" .}}
    component: webserver
    release: {{ .Release.Name }}
  annotations:
    {{ range $key, $value := .Values.ingress.webserver.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.webserver.path }}
            backend:
              serviceName: webserver
              servicePort: webserver
      host: {{ .Values.ingress.webserver.host }}
  tls:
{{ toYaml .Values.ingress.webserver.tls | indent 4 }}
