apiVersion: v1
kind: ConfigMap
metadata:
    name: "{{template "application.name" .}}-env"
    labels:
        app: {{template "application.name" .}}
data:
    CONTAINER_REGISTRY_ADDRESS: {{ .Values.app.registry }}
    GITHUB_REPO: {{ .Values.app.repo }}
    GITHUB_BRANCH: {{ .Values.app.branch }}
    FLASK_ENV: {{ .Values.app.env }}
    FLASK_APP: run.py
    APP_PORT: "{{ .Values.app.port }}"
    DEPLOY_KEY_PATH: {{ .Values.app.deployKeyPath }}
    REPO_CLONE_PATH: {{ .Values.app.repoClonePath }}
