apiVersion: v1
kind: ConfigMap
metadata:
    name: "{{template "application.name" .}}-env"
    labels:
        app: {{template "application.name" .}}
data:
    CONTAINER_REGISTRY_ADDRESS: {{ .Values.app.registry }}
    GITHUB_REPO: {{ .Values.app.repo }}
    FLASK_ENV: {{ .Values.app.env }}
    FLASK_APP: run.py
    FLASK_DATABASE_URI: {{ .Values.app.db }}
    APP_PORT: "{{ .Values.app.port }}"
