apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: {{template "application.name" .}}
    component: webserver
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{template "application.name" .}}
    component: webserver
    release: {{ .Release.Name }}
  ports:
  - name: webserver
    protocol: TCP
    port: 80
    targetPort: 80
status:
  loadBalancer: {}
